- path : /
  name: index
  controller: flamingo.render(tpl="index")

- path : /shop
  name: shop
  controller: flamingo.render(tpl="shop")

- path : /cart
  name: cart
  controller: flamingo.render(tpl="cart")